---

acme_sh_become_user: "root"

acme_sh_dependencies: ["git", "wget"]

acme_sh_git_url: "https://github.com/Neilpang/acme.sh"
acme_sh_git_version: "master"
acme_sh_git_update: False
acme_sh_git_clone_dest: "$HOME/acme.sh"

#acme_sh_upgrade: False
acme_sh_uninstall: False

#acme_sh_account_email: ""

acme_sh_renew_time_in_days: 90

#acme_sh_copy_certs_to_path: "/etc/ssl/ansible"

acme_sh_list_domains: True

acme_sh_default_staging: True

#acme_sh_default_force_issue: False
#acme_sh_default_force_renew: False

acme_sh_default_debug: False

acme_sh_default_dns_provider: "dns_aws"
acme_sh_default_dns_provider_api_keys: {}
acme_sh_default_dns_sleep: 60

acme_sh_default_extra_flags_issue: ""
acme_sh_default_extra_flags_renew: ""
acme_sh_default_extra_flags_install_cert: ""
